from selenium import webdriver
from common import getexcel
import time
from common import configHttp
content=configHttp.ConfigHttp()
user=getexcel.read_xls("user.xlsx","register").dict_xls()

for i in range(len(user)):
    options = webdriver.ChromeOptions()
    options.add_argument('disable-infobars')
    driver = webdriver.Chrome(options=options)
    driver.maximize_window()
    login_url = content.set_url("/pudge/login")
    driver.get(login_url)
    time.sleep(3)
    element1=driver.find_element_by_xpath("//input[@type='text']")
    element1.send_keys(user[i]['phone'])
    time.sleep(1)
    element2=driver.find_element_by_xpath("//input[@type='password']")
    element2.send_keys(user[i]['password'])
    element3=driver.find_element_by_xpath("//button[@type='submit']")
    element3.click()
    time.sleep(3)
    element4 = driver.find_element_by_link_text("我的账户")
    element4.click()
    time.sleep(3)
    element5 = driver.find_element_by_xpath("//div/div[1]/div[1]/a")
    element5.click()
    time.sleep(3)
    element6 = driver.find_element_by_xpath("//input[@placeholder='请输入真实姓名']")
    element6.send_keys(user[i]['name'])
    element7 = driver.find_element_by_xpath("//input[@placeholder='请输入身份证号']")
    element7.send_keys(user[i]['idcard'])
    element8 = driver.find_element_by_xpath("//button[@type='submit']")
    element8.click()
    time.sleep(3)
    element9 = driver.find_element_by_id('bankcardNo')
    element9.send_keys(user[i]['bankcardno'])
    element10 = driver.find_element_by_xpath("//input[@id='mobile']")
    element10.send_keys(user[i]['phone'])
    element11 = driver.find_element_by_xpath("//input[@id='sendSmsVerify']")
    element11.click()
    time.sleep(3)
    element112 = driver.find_element_by_class_name("submitBtn-2")
    element112.click()
    time.sleep(2)
    element111 = driver.find_element_by_id("smsCode")
    element111.send_keys("111111")
    element12 = driver.find_element_by_id("password")
    element12.send_keys(user[i]['tradeno'])
    element13 = driver.find_element_by_id("confirmPassword")
    element13.send_keys(user[i]['tradeno'])
    element14 = driver.find_element_by_id("nextButton")
    element14.click()
    time.sleep(10)
    driver.close()
